echo "Convertir iconos quitar ALFA de png a bmp"
sips -s format bmp icon-1024.png --out icon-1024.bmp
sips -s format bmp icon-108@2x.png --out icon-108@2x.bmp
sips -s format bmp icon-20.png --out icon-20.bmp
sips -s format bmp icon-20@2x.png --out icon-20@2x.bmp
sips -s format bmp icon-20@3x.png --out icon-20@3x.bmp
sips -s format bmp icon-24@2x.png --out icon-24@2x.bmp
sips -s format bmp icon-27.5@2x.png --out icon-27.5@2x.bmp
sips -s format bmp icon-29.png --out icon-29.bmp
sips -s format bmp icon-29@2x.png --out icon-29@2x.bmp
sips -s format bmp icon-29@3x.png --out icon-29@3x.bmp
sips -s format bmp icon-40.png --out icon-40.bmp
sips -s format bmp icon-40@2x.png --out icon-40@2x.bmp
sips -s format bmp icon-40@3x.png --out icon-40@3x.bmp
sips -s format bmp icon-44@2x.png --out icon-44@2x.bmp
sips -s format bmp icon-50.png --out icon-50.bmp
sips -s format bmp icon-50@2x.png --out icon-50@2x.bmp
sips -s format bmp icon-60.png --out icon-60.bmp
sips -s format bmp icon-60@2x.png --out icon-60@2x.bmp
sips -s format bmp icon-60@3x.png --out icon-60@3x.bmp
sips -s format bmp icon-72.png --out icon-72.bmp
sips -s format bmp icon-72@2x.png --out icon-72@2x.bmp
sips -s format bmp icon-76.png --out icon-76.bmp
sips -s format bmp icon-76@2x.png --out icon-76@2x.bmp
sips -s format bmp icon-83.5@2x.png --out icon-83.5@2x.bmp
sips -s format bmp icon-86@2x.png --out icon-86@2x.bmp
sips -s format bmp icon-98@2x.png --out icon-98@2x.bmp
sips -s format bmp icon-small.png --out icon-small.bmp
sips -s format bmp icon-small@2x.png --out icon-small@2x.bmp
sips -s format bmp icon-small@3x.png --out icon-small@3x.bmp
sips -s format bmp icon.png --out icon.bmp
echo "Creando png"
sips -s format png icon-1024.bmp --out icon-1024.png
sips -s format png icon-108@2x.bmp --out icon-108@2x.png
sips -s format png icon-20.bmp --out icon-20.png
sips -s format png icon-20@2x.bmp --out icon-20@2x.png
sips -s format png icon-20@3x.bmp --out icon-20@3x.png
sips -s format png icon-24@2x.bmp --out icon-24@2x.png
sips -s format png icon-27.5@2x.bmp --out icon-27.5@2x.png
sips -s format png icon-29.bmp --out icon-29.png
sips -s format png icon-29@2x.bmp --out icon-29@2x.png
sips -s format png icon-29@3x.bmp --out icon-29@3x.png
sips -s format png icon-40.bmp --out icon-40.png
sips -s format png icon-40@2x.bmp --out icon-40@2x.png
sips -s format png icon-40@3x.bmp --out icon-40@3x.png
sips -s format png icon-44@2x.bmp --out icon-44@2x.png
sips -s format png icon-50.bmp --out icon-50.png
sips -s format png icon-50@2x.bmp --out icon-50@2x.png
sips -s format png icon-60.bmp --out icon-60.png
sips -s format png icon-60@2x.bmp --out icon-60@2x.png
sips -s format png icon-60@3x.bmp --out icon-60@3x.png
sips -s format png icon-72.bmp --out icon-72.png
sips -s format png icon-72@2x.bmp --out icon-72@2x.png
sips -s format png icon-76.bmp --out icon-76.png
sips -s format png icon-76@2x.bmp --out icon-76@2x.png
sips -s format png icon-83.5@2x.bmp --out icon-83.5@2x.png
sips -s format png icon-86@2x.bmp --out icon-86@2x.png
sips -s format png icon-98@2x.bmp --out icon-98@2x.png
sips -s format png icon-small.bmp --out icon-small.png
sips -s format png icon-small@2x.bmp --out icon-small@2x.png
sips -s format png icon-small@3x.bmp --out icon-small@3x.png
sips -s format png icon.bmp --out icon.png